from __future__ import annotations

import json

import pandas as pd

from milan.analysis.profiling import profile_area
from milan.config import load_config
from milan.data.loader import load_area, target_areas

if __name__ == "__main__":
    cfg = load_config()
    (cfg.results / "tables").mkdir(parents=True, exist_ok=True)
    train = cfg.split_cols("train")

    rows = {}
    for area in target_areas(cfg):
        series = load_area(cfg, area)[train]
        rows[area] = profile_area(series, period=cfg.slots_per_day)
        print(f"profiled square {area}")

    frame = pd.DataFrame(rows).T
    frame.index.name = "square_id"
    frame.to_csv(cfg.results / "tables" / "profiles.csv")
    print(frame.T.to_string(float_format=lambda v: f"{v:,.4f}"))

    # --- Pre-registration -------------------------------------------------
    # H1: strongly periodic, low-entropy areas favour the low-capacity linear
    # model; high-entropy, bursty areas favour nonlinear capacity (TCN/GRU).
    # Rank by a simple composite: high seasonal strength and low entropy => predictable.
    score = (frame["seasonal_strength"] - frame["perm_entropy"] - frame["spectral_entropy"])
    ordering = score.sort_values(ascending=False)
    prediction = {
        "hypothesis": (
            "H1: areas with high seasonal strength and low permutation/spectral entropy "
            "favour DLinear; areas with high entropy and high burstiness favour TCN/GRU."
        ),
        "predictability_score": {int(k): float(v) for k, v in score.items()},
        "most_to_least_predictable": [int(a) for a in ordering.index],
        "predicted_winner_by_area": {
            int(area): ("dlinear" if score[area] >= score.median() else "tcn_or_gru")
            for area in frame.index
        },
        "recorded_before_reading_any_forecast_result": True,
    }
    path = cfg.results / "tables" / "prediction.json"
    path.write_text(json.dumps(prediction, indent=2))
    print("\nPRE-REGISTERED PREDICTION")
    print(json.dumps(prediction, indent=2))
    print(f"\nwritten to {path} -- do not edit this file after reading results")


